# DC-CPT reproducibility environment
# Build:  docker build -t dc-cpt .
# Run:    docker run -it -v $(pwd)/data:/workspace/data -v $(pwd)/results:/workspace/results dc-cpt

FROM python:3.11-slim

WORKDIR /workspace

# system dependencies for h5py, scikit-image, matplotlib
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libhdf5-dev \
    libgl1 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src/
COPY docs/ ./docs/

# data/ and results/ are expected to be mounted as volumes at runtime,
# not baked into the image (raw NIST data is multi-GB, and results are
# regenerated by running the scripts)
RUN mkdir -p data/raw data/processed results/tables results/figures

CMD ["/bin/bash"]
